---
  - name: Install dependencias 
    ansible.builtin.apt:
      pkg:
        - apache2 
        - ghostscript
        - libapache2-mod-php
        - mysql-server
        - php
        - php-bcmath
        - php-curl
        - php-imagick
        - php-intl
        - php-json
        - php-mbstring
        - php-mysql
        - php-xml
        - php-zip
        - python3-pymysql
      state: latest
      update_cache: yes
    become: yes
  - name: Cria uma tabela
    community.mysql.mysql_db:
      name: '{{ wp_db_name }}'
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
    become: yes

  - name: Cria um usuário 'wordpress_user' e senha '12345' com alguns privilégios na database
    community.mysql.mysql_user:
      name: '{{ wp_db_user }}'
      password: '{{ wp_db_pass }}'
      priv: '{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
      host: {{ item }}
    with_items:
    - 'localhost'
    - '127.0.0.1'
    - '{{ wp_ip}}'
    become: yes
  - name: Configura o arquivo wp-config.php com os dados corretos do banco de dados
    ansible.builtin.replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: "127.0.0.1"
      replace: "0.0.0.0"
    become: yes
    notify:
      - restart apache